# Generated by Django 2.1.7 on 2021-02-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('rollnumber', models.IntegerField(max_length=10)),
            ],
        ),
    ]
